### PR TITLE
Fix RemoveUnused tool for crash caused by PyGObject problem

### PR DESCRIPTION
**Pull request by prculley**
Fixes #11634  AttributeError: 'ListStore' object has no attribute 'sort_new_with_model'

PyGObject 3.26.1 (and possibly earlier) has mistakenly removed the original function in trying to fix something else.  It appears that it will be fixed again in a newer release, but for now we need to try both ways of creating a child model.

### CODE REVIEW

**Comment by lordemannd** [comment]
after adding this, it seems to work with the New Libs version of 5.1.2 (python3.8.2) but when I go back to original 5.1.2 (python3.6.4) I get the following error:

16086: ERROR: tool.py: line 257: Failed to start tool.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.2-working\gramps\gui\plug\tool.py", line 253, in gui_tool
    callback = callback)
  File "C:\Program Files\GrampsAIO64-5.1.2-working\gramps\plugins\tool\removeunused.py", line 127, in __init__
    self.init_gui()
  File "C:\Program Files\GrampsAIO64-5.1.2-working\gramps\plugins\tool\removeunused.py", line 175, in init_gui
    self.sort_model = Gtk.TreeModelSort.new_with_model(self.real_model)
AttributeError: type object 'TreeModelSort' has no attribute 'new_with_model'

**Comment by lordemannd** [comment]
how should prerequisite checker adapt to this?
